
V1

Welcome to coreedited. This is a collection of extensions
to help get started with Core linux. It is not intended to be a 
replacement for our distribution. 

In fact, if you have net access you will not need any of the support
extensions included here, as extensions in the repository will always be 
more current.

Booting from this CD will first load your regular extensions, then load the
support extensions for networking, installation, and remastering. Use the
boot option base to skip loading any user extensions.


Press ESC to return to the main menu.
Press F2, F3, or F4 to view additional boot options.

